services:
  database:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./backend/.env
    ports:
      - "5050:80"
    networks:
      - app-network
    depends_on:
      - database

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: todolist-backend
    networks:
      - app-network
    depends_on:
      - database
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - todolist-backend_node-modules:/app/node_modules

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  postgres-data:
  todolist-backend_node-modules:


networks:
  app-network:
